language: rust
install:
  - sudo apt-get install python3
before_script:
  - wget --no-check-certificate -i ./etc/files.txt -P ./files
  - make depend
script:
  - make debug
  - make release
  - make test
  - make bench
  - make doc
  - ./bin/debug/euler
  - ./bin/release/euler
  - (cd ./pkg/integer && cargo test  --verbose)
  - (cd ./pkg/integer && cargo bench --verbose)
  - (cd ./pkg/seq     && cargo test  --verbose)
  - (cd ./pkg/seq     && cargo bench --verbose)
  - (cd ./pkg/prime   && cargo test  --verbose)
  - (cd ./pkg/prime   && cargo bench --verbose)
  - cargo build --verbose
  - ./target/euler
  - cargo build --verbose --release
  - ./target/release/euler
  - cargo test  --verbose
  - cargo bench --verbose
  - cargo doc   --verbose
