language: rust
sudo: false

env:
  global:
    - secure: JA2ejwXX1SiBSJiEDfcML1866SfS/3Tefqy53rdlKiO3CzwC/Ktvt0kmUvrcgSa6p6vD+p8UzhqoMdApnTdcM93DWxhYrkc9eF6MiQK2V0AJc/2Im1braFTcPzKgj/0NhuSY10OrRO24mxcF3/olVMs4Nig5qeH5NmF8COJ+OPo=

script:
  - cargo run --bin euler --release
  - cargo test
  - cargo test -p cont_frac
  - cargo test -p integer
  - cargo test -p iter
  - cargo test -p matrix
  - cargo test -p playing_card
  - cargo test -p polynomial
  - cargo test -p prime
  - cargo test -p seq
  - cargo test -p tsort
  - cargo test -p union_find
  - cargo bench
  - cargo bench -p cont_frac
  - cargo bench -p integer
  - cargo bench -p iter
  - cargo bench -p matrix
  - cargo bench -p playing_card
  - cargo bench -p polynomial
  - cargo bench -p prime
  - cargo bench -p seq
  - cargo bench -p tsort
  - cargo bench -p union_find
  - cargo doc

after_success:
  - cd target
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
