before_install:
  - sudo apt-get update
install:
  - sudo apt-get install python3
  - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xfz rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - (cd rust-nightly-x86_64-unknown-linux-gnu/ && sudo ./install.sh)
before_script:
  - rustc --version
  - wget -i ./etc/files.txt -P ./files
  - make depend
script:
  - make debug
  - make release
  - make test
  - make bench
  - make doc
  - ./bin/debug/euler
  - ./bin/release/euler
