language: rust
install:
  - sudo apt-get install python3
before_script:
  - wget -i ./etc/files.txt -P ./files
  - make depend
script:
  - make debug
  - make release
  - make test
  - make bench
  - make doc
  - ./bin/debug/euler
  - ./bin/release/euler
  - cargo build --verbose
  - ./target/euler
  - cargo build --verbose --release
  - ./target/release/euler
  - cargo test --verbose
  - cargo bench --verbose
  - cargo doc --verbose
