language: rust
install:
  - sudo apt-get install python3
before_script:
  - wget --no-check-certificate -i ./etc/files.txt -P ./files
  - make -s depend
script:
  - make -s debug
  - make -s release
  - make -s test
  - make -s bench
  - make -s doc
  - ./bin/debug/euler
  - ./bin/release/euler
  - cargo run --name euler
  - cargo run --name euler --release
  - cargo test
  - cargo test -p integer
  - cargo test -p seq
  - cargo test -p prime
  - cargo bench
  - cargo bench -p integer
  - cargo bench -p seq
  - cargo bench -p prime
  - cargo doc
