language: rust
sudo: false
dist: trusty

cache:
  cargo: true
  directories:
    - .cache

rust:
  - nightly
  # - beta
  # - stable

script:
  - |
      cargo build --all --release &&
      cargo run --release --bin euler &&
      cargo test --all &&
      cargo bench --all &&
      cargo doc --all --no-deps
