language: rust
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
rust:
  - nightly
  # - beta
  # - stable

before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH
  - export KCOV="${TRAVIS_BUILD_DIR}/kcov/build/src/kcov --verify --exclude-pattern=/.cargo --coveralls-id=${TRAVIS_JOB_ID} ${TRAVIS_BUILD_DIR}/coverage"
  - wget https://github.com/SimonKagstrom/kcov/archive/master.zip
  - unzip master.zip
  - mv kcov-master kcov - mkdir kcov/build
  - cd kcov/build
  - cmake ..
  - make
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cargo test ${CARGO_FLAGS} --all
  - cargo build ${CARGO_FLAGS} --release
  - cargo run ${CARGO_FLAGS} --release --bin euler
  # `cargo bench --all` is not supported: (rust-lang/cargo#2878)
  # - cargo bench ${CARGO_FLAGS} --all
  - set -e
  - |
    for PKG in $(find pkg -mindepth 1 -maxdepth 1 -type d -printf '%f\n'); do
      echo cargo bench ${CARGO_FLAGS} -p ${PKG}
      cargo bench ${CARGO_FLAGS} -p ${PKG}
    done
  - cargo bench ${CARGO_FLAGS}
  - cargo doc ${CARGO_FLAGS}

after_success:
  - travis-cargo --only ${DOC_UPLOAD_VERSION} doc-upload
  # run tests again with gathering coverage information
  # doc tests are not being run.
  - |
      for PKG in $(echo ${SUB_PKGS}); do
        ${KCOV} ./target/debug/deps/${PKG}-*
      done
  - |
      for EXE in ./target/debug/euler-* ./target/debug/p???-*; do
        ${KCOV} ${EXE}
      done

env:
  global:
    - SUB_PKGS="cont_frac integer iter playing_card prime seq"
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - DOC_UPLOAD_VERSION=nightly
    - CARGO_FLAGS="-j1"
