language: rust
install:
  - sudo apt-get install python3
before_script:
  - wget --no-check-certificate -i ./etc/files.txt -P ./files
  - make depend
script:
  - make debug
  - make release
  - make test
  - make bench
  - make doc
  - ./bin/debug/euler
  - ./bin/release/euler
  - cargo run --bin euler --verbose
  - cargo run --bin euler --release --verbose
  - cargo test --verbose
  - cargo test -p cont_frac    --verbose
  - cargo test -p integer      --verbose
  - cargo test -p iter         --verbose
  - cargo test -p matrix       --verbose
  - cargo test -p playing_card --verbose
  - cargo test -p polynomial   --verbose
  - cargo test -p prime        --verbose
  - cargo test -p seq          --verbose
  - cargo test -p tsort        --verbose
  - cargo bench --verbose
  - cargo bench -p cont_frac    --verbose
  - cargo bench -p integer      --verbose
  - cargo bench -p iter         --verbose
  - cargo bench -p matrix       --verbose
  - cargo bench -p playing_card --verbose
  - cargo bench -p polynomial   --verbose
  - cargo bench -p prime        --verbose
  - cargo bench -p seq          --verbose
  - cargo bench -p tsort        --verbose
  - cargo doc --verbose

