language: rust
install:
  - sudo apt-get install python3
before_script:
  - wget --no-check-certificate -i ./etc/files.txt -P ./files
  - make depend
script:
  - make debug
  - make release
  - make test
  - make bench
  - make doc
  - ./bin/debug/euler
  - ./bin/release/euler
  - cargo run --bin euler --verbose
  - cargo run --bin euler --release --verbose
  - cargo test --verbose
  - cargo test -p integer --verbose
  - cargo test -p seq --verbose
  - cargo test -p prime --verbose
  - cargo bench --verbose
  - cargo bench -p integer --verbose
  - cargo bench -p seq --verbose
  - cargo bench -p prime --verbose
  - cargo doc --verbose

