before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly python3
before_script:
  - rustc --version
  - wget -i ./etc/files.txt -P ./files
  - make depend
script:
  - make debug
  - make release
  - make test
  - make bench
  - ./bin/debug/euler
  - ./bin/release/euler
