language: rust
install:
  - sudo apt-get install python3
before_script:
  - wget --no-check-certificate -i ./etc/files.txt -P ./files
  - make depend
script:
  - make -s debug
  - make -s release
  - make -s test
  - make -s bench
  - make -s doc
  - ./bin/debug/euler
  - ./bin/release/euler
  - (cd ./pkg/integer && cargo test)
  - (cd ./pkg/integer && cargo bench)
  - (cd ./pkg/seq     && cargo test)
  - (cd ./pkg/seq     && cargo bench)
  - (cd ./pkg/prime   && cargo test)
  - (cd ./pkg/prime   && cargo bench)
  - cargo build
  - ./target/euler
  - cargo build --release
  - ./target/release/euler
  - cargo test
  - cargo bench
  - cargo doc
