language: rust
install:
  - sudo apt-get install python3
before_script:
  - wget --no-check-certificate -i ./etc/files.txt -P ./files
  - make depend
script:
  - make debug -s
  - make release -s
  - make test -s
  - make bench -s
  - make doc -s
  - ./bin/debug/euler
  - ./bin/release/euler
  - cargo run --bin euler --release
  - cargo test
  - cargo test -p cont_frac
  - cargo test -p integer
  - cargo test -p iter
  - cargo test -p matrix
  - cargo test -p playing_card
  - cargo test -p polynomial
  - cargo test -p prime
  - cargo test -p seq
  - cargo test -p tsort
  - cargo bench
  - cargo bench -p cont_frac
  - cargo bench -p integer
  - cargo bench -p iter
  - cargo bench -p matrix
  - cargo bench -p playing_card
  - cargo bench -p polynomial
  - cargo bench -p prime
  - cargo bench -p seq
  - cargo bench -p tsort
  - cargo doc

