[package]

name = "ProjectEulerRust"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]

[lib]

name = "common"

[dependencies.glob]

git = "https://github.com/rust-lang/glob"

[dependencies.seq]

path = "./pkg/seq"

[dependencies.prime]

path = "./pkg/prime"
