[package]
name = "ProjectEulerRust"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]

[lib]
name = "common"

[dependencies.curl]
git = "https://github.com/carllerche/curl-rust"

[dependencies.glob]
git = "https://github.com/rust-lang/glob"

[dependencies.num]
git = "https://github.com/rust-lang/num"

[dependencies.time]
git = "https://github.com/rust-lang/time"

[dependencies.cont_frac]
path = "./pkg/cont_frac"

[dependencies.integer]
path = "./pkg/integer"

[dependencies.iter]
path = "./pkg/iter"

[dependencies.matrix]
path = "./pkg/matrix"

[dependencies.prime]
path = "./pkg/prime"

[dependencies.playing_card]
path = "./pkg/playing_card"

[dependencies.seq]
path = "./pkg/seq"

[dependencies.tsort]
path = "./pkg/tsort"
