[package]
name = "ProjectEulerRust"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]

[lib]
name = "common"

[dependencies.glob]
git = "https://github.com/rust-lang/glob"

[dependencies.num]
git = "https://github.com/rust-lang/num"

[dependencies.curl]
git = "https://github.com/carllerche/curl-rust"

[dependencies.seq]
path = "./pkg/seq"

[dependencies.prime]
path = "./pkg/prime"

[dependencies.integer]
path = "./pkg/integer"
