[package]
name = "ProjectEulerRust"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
license-file="LICENSE"
readme = "README.md"
repository = "https://github.com/gifnksm/ProjectEulerRust"
keywords = ["algebra", "algorithms", "computation", "mathematics", "numerics"]
description = "Solving Project Euler with Rust lang."

[lib]
name = "common"

[dependencies]
curl = "*"
getopts = "*"
glob = "*"
num = "*"
rustc-serialize = "*"
time = "*"

[dependencies.cont_frac]
path = "./pkg/cont_frac"

[dependencies.integer]
path = "./pkg/integer"

[dependencies.iter]
path = "./pkg/iter"

[dependencies.matrix]
path = "./pkg/matrix"

[dependencies.playing_card]
path = "./pkg/playing_card"

[dependencies.polynomial]
path = "./pkg/polynomial"

[dependencies.prime]
path = "./pkg/prime"

[dependencies.seq]
path = "./pkg/seq"

[dependencies.tsort]
path = "./pkg/tsort"

[dependencies.union_find]
path = "./pkg/union_find"
