[package]
name = "integer"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
workspace = "../../"

[dependencies]
num-integer = "0.1"
num-traits = "0.2"

[dependencies.num-bigint]
version = "0.2"
optional = true
default-features = false
features = ["std"]

[features]
bigint = ["num-bigint"]
serde = ["num-bigint/serde"]

default = []
