[package]
name = "integer"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
workspace = "../../"

[dependencies]
num-integer = "0.1"
num-traits = "0.1"

[dependencies.num-bigint]
version = "0.1"
optional = true
default-features = false

[features]
bigint = ["num-bigint"]
serde = ["num-bigint/serde"]
rustc-serialize = ["num-bigint/rustc-serialize"]

default = []
